### ISSUE TITLE
Wrong Roll for Iniciative

### ISSUE THREAD

**Issue by Vitu-zin** [tech-ticks/foundry-pokerole#18]
The iniciative macro is rolling a Dex+AlertD6, the correct roll should be a 1d6+Dex+Alert.

**Comment by Vitu-zin** [comment]
If you roll directly from the sheet it occurs, but if roll adding the pokemon on the encounter table and rolling from there works fine.

**Comment by tech-ticks** [comment]
Reopening this since I feel like this should be changed to the same formula on the sheet as well to make it less confusing
