### ISSUE TITLE
Allow specifying a custom modifier on Initiative rolls

### ISSUE THREAD

**Issue by Midaychi** [tech-ticks/foundry-pokerole#30]
When the turn rolls over to a new one, it resets the multi action penalty rather than maintaining it.

Also there's nowhere to easily add bonus dice to initiative without modifying attributes/skills (say from a quick claw or an awareness charm)

**Comment by tech-ticks** [comment]
> When the turn rolls over to a new one, it resets the multi action penalty rather than maintaining it.

This one is working as intended since the penalty is based on how many actions have been taken in a given round.

**Comment by tech-ticks** [comment]
As a workaround, the DM can edit the initiative value after the roll.

**Comment by Midaychi** [comment]
Would be nice to have a rolling turn pass feature then.

In core each participant takes a turn using an action in order of initiative, and it keeps looping around till nobody takes an action and the round passes to a new one.

Replicating this in foundry means you either don't pass turns using the foundry's interface, or you spend a lot of time manually fiddling with initiative.  At that point you might as well do initiative manually instead of using the built-in foundry tool.

**Comment by tech-ticks** [comment]
You can navigate back to the start of a turn to get the right behavior without resetting the tracker but yeah, there's definitely room for improvement to make this less annoying. There will probably be a button or some prompt to go back to the first participant in a turn.

**Comment by tech-ticks** [comment]
Added as a field in Actor settings (cog icon in Biography)
